[package]
name = "discord-theme"
version = "0.1.0"
authors = ["Bendi11 <bkliebmann@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.8" # For config file format
console = "0.14.1" # For formatted console

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'